url:
  order:
    host: http://localhost:9092
zeus-ref-data:
  api:
    version: 1.0.0
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zeusrefdatadb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: zeusrefdataapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
  flyway:
    user: zeusrefdataadmin
    password: password
    clean-disabled: false
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/refdata.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
