openapi: 3.0.1
info:
  title: Zeus Reference Data API
  contact:
    name: Balaji Varadharajan
    url: http://www.zeus.com
    email: vbalaji215@outlook.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/License-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Development Server
paths:
  /api/v1/ref-data/x-walk/internal:
    post:
      tags:
      - X-Walk
      description: Retrieves the internal ref data code for the external ref data
        code provided
      operationId: Get Internal Code for External Code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XWalkRequest'
        required: true
      responses:
        "404":
          description: The external ref data code provided was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
        "200":
          description: The internal ref data code was retrieved for the external ref
            data code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XWalkResponse'
  /api/v1/ref-data/x-walk/external:
    post:
      tags:
      - X-Walk
      description: Retrieves the external ref data code for the internal ref data
        code provided
      operationId: Get External code for Internal Code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XWalkRequest'
        required: true
      responses:
        "404":
          description: The internal ref data code provided was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
        "200":
          description: The external ref data code was retrieved for the internal ref
            data code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XWalkResponse'
  /api/v1/ref-data/internal:
    post:
      tags:
      - internal-ref-data
      description: Validate if the code is present in reference data
      operationId: Validate internal REF-DATA code
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalRefDataRequest'
        required: true
      responses:
        "200":
          description: The code was validated against the internal reference data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalRefDataResponse'
        "404":
          description: The internal list provided was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
  /api/v1/ref-data/internal/list:
    post:
      tags:
      - internal-ref-data
      description: Validate if the codes in the list is present in reference data
      operationId: Validate internal ref data codes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalRefDataRequestList'
        required: true
      responses:
        "404":
          description: The internal list provided was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
        "200":
          description: The codes were validated against the internal reference data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalRefDataResponseList'
  /api/v1/ref-data/internal/list-types:
    get:
      tags:
      - internal-ref-data
      description: Get all the internal list types
      operationId: Get All internal list types
      responses:
        "200":
          description: Successfully retrieved all the internal list types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalListTypesDto'
    post:
      tags:
      - internal-ref-data
      description: Get all the internal list codes for multiple list types
      operationId: Get codes for list types
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalListTypesDto'
        required: true
      responses:
        "404":
          description: Unable to find any internal list for the given list types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
        "200":
          description: Successfully retrieved all the internal ref data list for the
            internal list types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalListTypeDto'
  /api/v1/ref-data/internal/{listTypeName}:
    get:
      tags:
      - internal-ref-data
      description: Get all the internal list codes for the given list type
      operationId: Get codes by List type
      parameters:
      - name: listTypeName
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Unable to find any internal list for the given list type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
        "200":
          description: Successfully retrieved all the internal ref data list for the
            internal list type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalListTypeDto'
  /:
    get:
      tags:
      - welcome-resource
      operationId: welcome_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    XWalkRequest:
      required:
      - externalSourceName
      - listCode
      - listTypeName
      type: object
      properties:
        listCode:
          type: string
          description: The internal or external ref data code for which the cross
            walk value is requested
          example: SSN
        listTypeName:
          type: string
          description: "The name of the list type that the code is associated. If\
            \ the XWALK from external to internal then this is external list type\
            \ name, if from internal to external then this is internal list type name"
          example: Identifier
        externalSourceName:
          type: string
          description: The name of the external source that is involved in the cross-walk
          example: Identifier
    ApiException:
      type: object
      properties:
        exceptionCode:
          type: string
        exceptionMessage:
          type: string
    ApiExceptionList:
      type: object
      properties:
        exceptions:
          type: array
          items:
            $ref: '#/components/schemas/ApiException'
    XWalkResponse:
      type: object
      properties:
        internalListCode:
          type: string
          description: The internal list code
          readOnly: true
          example: SSN
        internalListTypeName:
          type: string
          description: The name of the internal list type
          readOnly: true
          example: Identifier
        externalListCode:
          type: string
          description: The external list code
          readOnly: true
          example: "34"
        externalListTypeName:
          type: string
          description: The name of the external list type
          readOnly: true
          example: Identifier
        externalSourceName:
          type: string
    InternalRefDataRequest:
      required:
      - internalListCode
      - internalListTypeName
      type: object
      properties:
        internalListCode:
          type: string
          description: The internal ref data code that needs to be validated
          example: SSN
        internalListTypeName:
          type: string
          description: The internal list that the code belongs to
          example: Identifier
    InternalRefDataResponse:
      type: object
      properties:
        internalListCode:
          type: string
          description: The internal ref data code that was validated
          example: SSN
        internalListTypeName:
          type: string
          description: The internal list type that  the code was validated against
          example: Identifier
        valid:
          type: boolean
          description: Indicates if the code provided is valid or not
          example: true
    InternalRefDataRequestList:
      required:
      - internalRefDataRequestList
      type: object
      properties:
        internalRefDataRequestList:
          type: array
          description: The list of internal ref data codes that needs to be validated
          items:
            $ref: '#/components/schemas/InternalRefDataRequest'
    InternalRefDataResponseList:
      type: object
      properties:
        responseList:
          type: array
          items:
            $ref: '#/components/schemas/InternalRefDataResponse'
    InternalListTypeDto:
      required:
      - displayName
      - internalListTypeName
      type: object
      properties:
        internalListTypeSK:
          type: string
          description: The key of the internal list type
          format: uuid
          readOnly: true
          example: 657cfd75-634e-49f1-9556-4d79f79848ec
        internalListTypeName:
          type: string
          description: Internal list type name
          example: Identifier
        internalListTypeDesc:
          type: string
          description: Internal list type description
          example: Contains the list of all the internal identifiers
        displayName:
          type: string
          description: Display name of the list type
          example: Identifier
        internalRefDataList:
          type: array
          description: The list of the internal ref-data codes that are in the internal
            list
          items:
            $ref: '#/components/schemas/InternalRefData'
      description: Contains the list of all the internal reference data lists
    InternalListTypesDto:
      type: object
      properties:
        internalListTypes:
          type: array
          description: Contains the list of all the internal reference data lists
          items:
            $ref: '#/components/schemas/InternalListTypeDto'
    InternalRefData:
      required:
      - displayName
      type: object
      properties:
        listCode:
          type: string
        listTypeDto:
          $ref: '#/components/schemas/InternalListTypeDto'
        listCodeDesc:
          type: string
        displayName:
          type: string
          description: Display name of the list code
          example: Social Security Number
      description: The list of the internal ref-data codes that are in the internal
        list
