openapi: 3.0.1
info:
  title: Zeus Reference Data API
  contact:
    name: Balaji Varadharajan
    url: http://www.zeus.com
    email: vbalaji215@outlook.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/License-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Development Server
paths:
  /api/v1/xwalk/internal:
    post:
      tags:
      - x-walk-resource
      operationId: getInternalRefData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XWalkRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/XWalkResponse'
  /api/v1/xwalk/external:
    post:
      tags:
      - x-walk-resource
      operationId: getExternalRefData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XWalkRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/XWalkResponse'
  /api/v1/internal/refdata:
    post:
      tags:
      - internal-ref-data
      description: Validate if the code is present in reference data
      operationId: validateReferenceData
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InternalRefDataRequest'
        required: true
      responses:
        "404":
          description: The internal list provided was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
        "200":
          description: The code was validated against the internal reference data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalRefDataResponse'
  /api/v1/internal/refdata/{listTypeName}:
    get:
      tags:
      - internal-ref-data
      description: Get all the internal list codes for the given list type
      operationId: getInternalRefData_1
      parameters:
      - name: listTypeName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved all the internal ref data list for the
            internal list type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalRefDataList'
        "404":
          description: Unable to find any internal list for the given list type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiExceptionList'
components:
  schemas:
    XWalkRequest:
      type: object
      properties:
        listCode:
          type: string
        listTypeName:
          type: string
        externalSourceName:
          type: string
    ResponseMetadata:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        statusCode:
          type: integer
          format: int32
        status:
          type: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        reason:
          type: string
        message:
          type: string
        developerMessage:
          type: string
    XWalkResponse:
      type: object
      properties:
        responseMetadata:
          $ref: '#/components/schemas/ResponseMetadata'
        internalListCode:
          type: string
        internalListTypeName:
          type: string
        externalListCode:
          type: string
        externalListTypeName:
          type: string
        externalSourceName:
          type: string
    InternalRefDataRequest:
      required:
      - internalListCode
      - internalListTypeName
      type: object
      properties:
        internalListCode:
          type: string
          description: The internal ref data code that needs to be validated
          example: SSN
        internalListTypeName:
          type: string
          description: The internal list that the code belongs to
          example: Identifier
    ApiException:
      type: object
      properties:
        exceptionCode:
          type: string
        exceptionMessage:
          type: string
    ApiExceptionList:
      type: object
      properties:
        exceptions:
          type: array
          items:
            $ref: '#/components/schemas/ApiException'
    InternalRefDataResponse:
      type: object
      properties:
        responseMetadata:
          $ref: '#/components/schemas/ResponseMetadata'
        internalListCode:
          type: string
        internalListTypeName:
          type: string
        valid:
          type: boolean
    InternalRefData:
      type: object
      properties:
        listCode:
          type: string
        listTypeName:
          type: string
        listCodeDesc:
          type: string
    InternalRefDataList:
      type: object
      properties:
        internalRefDataList:
          type: array
          items:
            $ref: '#/components/schemas/InternalRefData'
